# Generated by Django 3.2.7 on 2021-09-17 13:43

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.CharField(default='AnanymousUser', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to=board.models.board_image_path),
        ),
    ]
