# Generated by Django 3.2.7 on 2021-09-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210909_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_processed',
            new_name='image',
        ),
    ]
